
module.exports = {
  IMAGE_UPLOADING: 'IMAGE_UPLOADING',
  IMAGE_UPLOAD_SUCCESS: 'IMAGE_UPLOAD_SUCCESS',
  IMAGE_UPLOAD_FAIL: 'IMAGE_UPLOAD_FAIL',
  POST_DELETING: 'POST_DELETING',
  POST_DELETED: 'POST_DELETED',
  POST_DELETE_FAIL: 'POST_DELETE_FAIL',
  POST_SAVING: 'POST_SAVING',
  POST_SAVED: 'POST_SAVED',
  POST_SAVE_FAIL: 'POST_SAVE_FAIL',
  THEME_CHANGING: 'THEME_CHANGING',
  THEME_CHANGED: 'THEME_CHANGED',
  THEME_CHANGE_FAIL: 'THEME_CHANGE_FAIL'
}
