module.exports = [
  {
    "label_zh":"水果",
    "types":[
      {
        "label_zh":"檸檬",
        "val":1,
        "label_en":"Lemon"
      },
      {
        "label_zh":"柑橘",
        "val":2,
        "label_en":"Orange"
      },
      {
        "label_zh":"萊姆",
        "val":3,
        "label_en":"Lime"
      },
      {
        "label_zh":"葡萄柚",
        "val":4,
        "label_en":"Grapefruit"
      },
      {
        "label_zh":"葡萄",
        "val":5,
        "label_en":"Grapes"
      },
      {
        "label_zh":"藍莓",
        "val":6,
        "label_en":"Blackberries"
      },
      {
        "label_zh":"蘋果",
        "val":7,
        "label_en":"Apple"
      },
      {
        "label_zh":"青蘋果",
        "val":8,
        "label_en":"Greenapple"
      },
      {
        "label_zh":"梨子",
        "val":9,
        "label_en":"Pear"
      },
      {
        "label_zh":"櫻桃",
        "val":10,
        "label_en":"Cherry"
      },
      {
        "label_zh":"李子",
        "val":11,
        "label_en":"Plum"
      },
      {
        "label_zh":"椰子",
        "val":12,
        "label_en":"Coconut"
      },
      {
        "label_zh":"桃子",
        "val":13,
        "label_en":"Peach"
      },
      {
        "label_zh":"奇異果",
        "val":14,
        "label_en":"Kiwi"
      },
      {
        "label_zh":"鳳梨",
        "val":15,
        "label_en":"Pineapple"
      },
      {
        "label_zh":"香蕉",
        "val":16,
        "label_en":"Banana"
      },
      {
        "label_zh":"西瓜",
        "val":17,
        "label_en":"Watermelon"
      },
      {
        "label_zh":"哈密瓜 ",
        "val":18,
        "label_en":"Melon"
      },
      {
        "label_zh":"蜜餞",
        "val":19,
        "label_en":"Date"
      },
      {
        "label_zh":"無花果",
        "val":20,
        "label_en":"Fig"
      },
      {
        "label_zh":"葡萄乾",
        "val":21,
        "label_en":"Raisin"
      },
      {
        "label_zh":"橄欖",
        "val":22,
        "label_en":"Olive"
      }
    ],
    "label_en":"Fruit"
  },
  {
    "label_zh":"穀物堅果",
    "types":[
      {
        "label_zh":"麥芽",
        "val":23,
        "label_en":"Malt"
      },
      {
        "label_zh":"大麥",
        "val":24,
        "label_en":"Barley"
      },
      {
        "label_zh":"小麥",
        "val":25,
        "label_en":"Wheat"
      },
      {
        "label_zh":"堅果",
        "val":26,
        "label_en":"Nuts"
      },
      {
        "label_zh":"榛果",
        "val":27,
        "label_en":"Hazelnut"
      },
      {
        "label_zh":"杏仁",
        "val":28,
        "label_en":"Almond"
      },
      {
        "label_zh":"植物油",
        "val":29,
        "label_en":"Vegeoil"
      }
    ],
    "label_en":"Grainnuts"
  },
  {
    "label_zh":"花草類",
    "types":[
      {
        "label_zh":"香草",
        "val":30,
        "label_en":"Vanilla"
      },
      {
        "label_zh":"藥草味",
        "val":31,
        "label_en":"Herb"
      },
      {
        "label_zh":"青草",
        "val":32,
        "label_en":"Grass"
      },
      {
        "label_zh":"乾草",
        "val":33,
        "label_en":"Hay"
      },
      {
        "label_zh":"玫瑰",
        "val":34,
        "label_en":"Rose"
      },
      {
        "label_zh":"紫羅蘭",
        "val":35,
        "label_en":"Violet"
      },
      {
        "label_zh":"茶葉",
        "val":36,
        "label_en":"Tea"
      },
      {
        "label_zh":"薄荷",
        "val":37,
        "label_en":"Mint"
      }
    ],
    "label_en":"Floral"
  },
  {
    "label_zh":"辛香料",
    "types":[
      {
        "label_zh":"胡椒",
        "val":38,
        "label_en":"Pepper"
      },
      {
        "label_zh":"辣椒",
        "val":39,
        "label_en":"Chili"
      },
      {
        "label_zh":"肉桂",
        "val":40,
        "label_en":"Cinnamon"
      },
      {
        "label_zh":"丁香",
        "val":41,
        "label_en":"Cloves"
      },
      {
        "label_zh":"薑",
        "val":42,
        "label_en":"Ginger"
      },
      {
        "label_zh":"肉豆蔻",
        "val":43,
        "label_en":"Nutmeg"
      }
    ],
    "label_en":"Spices"
  },
  {
    "label_zh":"甜味",
    "types":[
      {
        "label_zh":"焦糖",
        "val":44,
        "label_en":"Caramel"
      },
      {
        "label_zh":"甜味",
        "val":45,
        "label_en":"Sweet"
      },
      {
        "label_zh":"牛奶巧克力",
        "val":46,
        "label_en":"MilkChocolate"
      },
      {
        "label_zh":"黑巧克力",
        "val":47,
        "label_en":"DarkChocolate"
      },
      {
        "label_zh":"蜂蜜",
        "val":48,
        "label_en":"Honey"
      },
      {
        "label_zh":"奶油",
        "val":49,
        "label_en":"Butter"
      }
    ],
    "label_en":"Sweetness"
  },
  {
    "label_zh":"桶味",
    "types":[
      {
        "label_zh":"木桶",
        "val":50,
        "label_en":"Oak"
      },
      {
        "label_zh":"雪莉桶",
        "val":51,
        "label_en":"Sherry"
      },
      {
        "label_zh":"木頭",
        "val":52,
        "label_en":"Wood"
      },
      {
        "label_zh":"皮革",
        "val":53,
        "label_en":"Leather"
      },
      {
        "label_zh":"咖啡",
        "val":54,
        "label_en":"Coffee"
      },
      {
        "label_zh":"菸草",
        "val":55,
        "label_en":"Tabacco"
      }
    ],
    "label_en":"Oakgroup"
  },
  {
    "label_zh":"化學味",
    "types":[
      {
        "label_zh":"碘酒",
        "val":56,
        "label_en":"Iodine"
      },
      {
        "label_zh":"酒精味",
        "val":57,
        "label_en":"Alcohol"
      },
      {
        "label_zh":"腐敗",
        "val":58,
        "label_en":"Rotten"
      },
      {
        "label_zh":"酵母",
        "val":59,
        "label_en":"Yeast"
      },
      {
        "label_zh":"醋",
        "val":60,
        "label_en":"Vinegar"
      },
      {
        "label_zh":"煤油",
        "val":61,
        "label_en":"Kerosene"
      },
      {
        "label_zh":"塑膠",
        "val":62,
        "label_en":"Plastic"
      }
    ],
    "label_en":"Chemical"
  },
  {
    "label_zh":"其他",
    "types":[
      {
        "label_zh":"煙燻",
        "val":63,
        "label_en":"Smoke"
      },
      {
        "label_zh":"鹽",
        "val":64,
        "label_en":"Salt"
      },
      {
        "label_zh":"海草",
        "val":65,
        "label_en":"Tang"
      },
      {
        "label_zh":"土壤",
        "val":66,
        "label_en":"Earthy"
      },
      {
        "label_zh":"火腿",
        "val":67,
        "label_en":"Ham"
      },
      {
        "label_zh":"起司",
        "val":68,
        "label_en":"Cheese"
      }
    ],
    "label_en":"Others"
  }
]
