
// http://fontawesome.io/icons/
import 'vue-awesome/icons/chevron-left'
import 'vue-awesome/icons/pencil'
import 'vue-awesome/icons/home'
import 'vue-awesome/icons/bars'
import 'vue-awesome/icons/newspaper-o'
import 'vue-awesome/icons/glass'
import 'vue-awesome/icons/tree'
import 'vue-awesome/icons/tint'
import 'vue-awesome/icons/check-square-o'
import 'vue-awesome/icons/warning'
export const BACK_ICON = 'chevron-left'
export const PENCIL_ICON = 'pencil'
export const HOME_ICON = 'home'
export const BARS_ICON = 'bars'
export const NEWS_ICON = 'newspaper-o'
export const GLASS_ICON = 'glass'
export const SMELL_ICON = 'tree'
export const TASTE_ICON = 'tint'
export const SUMMARY_ICON = 'check-square-o'
export const WARNING_ICON = 'warning'
